//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub fn new_event(
  level level: Option(String),
  namespace namespace: Option(String),
  message message: String,
  variables variables: Option(String),
) {
  let sql =
    "INSERT INTO logs (level, namespace, message, variables) VALUES (?, ?, ?, ?)"
  #(sql, [
    dev.ParamNullable(option.map(level, fn(v) { dev.ParamString(v) })),
    dev.ParamNullable(option.map(namespace, fn(v) { dev.ParamString(v) })),
    dev.ParamString(message),
    dev.ParamNullable(option.map(variables, fn(v) { dev.ParamString(v) })),
  ])
}
