# Moved to just, kept here to preserve backwards compatibility.

[build-styles]
hide = true
description = "$just build-styles"
run = "just build-styles"

[build-server]
hide = true
description = "$just build-server"
run = "just build-server"

[build-client]
hide = true
description = "$just build-client"
run = "just build-client"

[build-server-release]
hide = true
description = "$just build-server-release"
run = "just build-server-release"

[clean-all]
hide = true
description = "$just clean-all"
run = "just clean-all"

[prefetch-gleam-deps]
hide = true
description = "$just prefetch-gleam-deps"
run = "prefetch-gleam-deps"

[create-data-dirs]
hide = true
run = "just create-data-dirs"

[bun-install]
hide = true
description = "$just bun-install"
run = "just bun-install"

[local-devel-prep]
hide = true
description = "$just local-devel-prep"
run = "just local-devel-prep"

[local-devel]
hide = true
description = "$just local-devel"
run = "just local-devel"

[local-devel-watch]
hide = true
description = "$just local-devel-watch"
run = "just local-devel-watch"
