name = "lumina_server"
version = "1.0.0"
target = "erlang"
licences = ["EUPL-1.2"]
[erlang]
application_start_module = "lumina_server"


[dependencies]
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
youid = ">= 1.6.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
collie = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
booklet = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 1.0.2 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 6.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
ewe = ">= 4.0.1 and < 5.0.0"
envoy = ">= 1.2.0 and < 2.0.0"
witness = ">= 2.0.0 and < 3.0.0"
logging = ">= 1.5.0 and < 2.0.0"
iv = ">= 1.4.4 and < 2.0.0"
mala = ">= 1.2.0 and < 2.0.0"
rasa = ">= 2.0.1 and < 3.0.0"
group_registry = ">= 1.0.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
argus = ">= 1.0.4 and < 2.0.0"
friendly_id = ">= 2.1.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.7.0 and < 5.0.0"
