[tools]
bun = "1.2.20"
"cargo:sqlx-cli" = "latest"
gleam = "1.15.0"
just = "latest"
"rust" = { version = "1.94.0", components = "rust-analyzer" }
watchexec = "latest"


[settings]
[settings.cargo]
binstall = false # This fails in some cases, watchexec can be compiled from source quickly enough
[settings.npm]
bun = true

[task_config]
includes = [
	"./mise/tasks/podman.toml",
	"./mise/tasks/format.toml",
	"./mise/tasks/check.toml",
	"./mise/tasks/run.toml",
	"./mise/tasks/moved-to-just.toml",
]
dir = "{{ config_root }}"
