name: test-fe-gleam
on:
    push:
        branches:
            - master
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: clippy
                  override: true
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "26.0.2"
                  gleam-version: "1.4.1"
                  rebar3-version: "3"
                  # elixir-version: "1.15.4"
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: "1.1.30"
            - run: bash ./build.sh --test
